package com.yeahmobi.yscheduler.model;

import com.yeahmobi.yscheduler.model.type.WorkflowInstanceStatus;
import java.util.Date;

public class TeamWorkflowInstanceStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_workflow_instance_status.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_workflow_instance_status.team_id
     *
     * @mbggenerated
     */
    private Long teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_workflow_instance_status.workflow_id
     *
     * @mbggenerated
     */
    private Long workflowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_workflow_instance_status.workflow_instance_id
     *
     * @mbggenerated
     */
    private Long workflowInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_workflow_instance_status.status
     *
     * @mbggenerated
     */
    private WorkflowInstanceStatus status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_workflow_instance_status.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_workflow_instance_status.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_workflow_instance_status.id
     *
     * @return the value of team_workflow_instance_status.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_workflow_instance_status.id
     *
     * @param id the value for team_workflow_instance_status.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_workflow_instance_status.team_id
     *
     * @return the value of team_workflow_instance_status.team_id
     *
     * @mbggenerated
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_workflow_instance_status.team_id
     *
     * @param teamId the value for team_workflow_instance_status.team_id
     *
     * @mbggenerated
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_workflow_instance_status.workflow_id
     *
     * @return the value of team_workflow_instance_status.workflow_id
     *
     * @mbggenerated
     */
    public Long getWorkflowId() {
        return workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_workflow_instance_status.workflow_id
     *
     * @param workflowId the value for team_workflow_instance_status.workflow_id
     *
     * @mbggenerated
     */
    public void setWorkflowId(Long workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_workflow_instance_status.workflow_instance_id
     *
     * @return the value of team_workflow_instance_status.workflow_instance_id
     *
     * @mbggenerated
     */
    public Long getWorkflowInstanceId() {
        return workflowInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_workflow_instance_status.workflow_instance_id
     *
     * @param workflowInstanceId the value for team_workflow_instance_status.workflow_instance_id
     *
     * @mbggenerated
     */
    public void setWorkflowInstanceId(Long workflowInstanceId) {
        this.workflowInstanceId = workflowInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_workflow_instance_status.status
     *
     * @return the value of team_workflow_instance_status.status
     *
     * @mbggenerated
     */
    public WorkflowInstanceStatus getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_workflow_instance_status.status
     *
     * @param status the value for team_workflow_instance_status.status
     *
     * @mbggenerated
     */
    public void setStatus(WorkflowInstanceStatus status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_workflow_instance_status.create_time
     *
     * @return the value of team_workflow_instance_status.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_workflow_instance_status.create_time
     *
     * @param createTime the value for team_workflow_instance_status.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_workflow_instance_status.update_time
     *
     * @return the value of team_workflow_instance_status.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_workflow_instance_status.update_time
     *
     * @param updateTime the value for team_workflow_instance_status.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_workflow_instance_status
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", teamId=").append(teamId);
        sb.append(", workflowId=").append(workflowId);
        sb.append(", workflowInstanceId=").append(workflowInstanceId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_workflow_instance_status
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TeamWorkflowInstanceStatus other = (TeamWorkflowInstanceStatus) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTeamId() == null ? other.getTeamId() == null : this.getTeamId().equals(other.getTeamId()))
            && (this.getWorkflowId() == null ? other.getWorkflowId() == null : this.getWorkflowId().equals(other.getWorkflowId()))
            && (this.getWorkflowInstanceId() == null ? other.getWorkflowInstanceId() == null : this.getWorkflowInstanceId().equals(other.getWorkflowInstanceId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_workflow_instance_status
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTeamId() == null) ? 0 : getTeamId().hashCode());
        result = prime * result + ((getWorkflowId() == null) ? 0 : getWorkflowId().hashCode());
        result = prime * result + ((getWorkflowInstanceId() == null) ? 0 : getWorkflowInstanceId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}