package com.yeahmobi.yscheduler.model.dao.mapper;

import com.yeahmobi.yscheduler.model.Attempt;
import com.yeahmobi.yscheduler.model.AttemptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AttemptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    int countByExample(AttemptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    int deleteByExample(AttemptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    int insert(Attempt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    int insertSelective(Attempt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    List<Attempt> selectByExampleWithBLOBsWithRowbounds(AttemptExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    List<Attempt> selectByExampleWithBLOBs(AttemptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    List<Attempt> selectByExampleWithRowbounds(AttemptExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    List<Attempt> selectByExample(AttemptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    Attempt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Attempt record, @Param("example") AttemptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Attempt record, @Param("example") AttemptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Attempt record, @Param("example") AttemptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Attempt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Attempt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attempt
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Attempt record);
}