package com.yeahmobi.yscheduler.model.dao.mapper;

import com.yeahmobi.yscheduler.model.ScheduleProgress;
import com.yeahmobi.yscheduler.model.ScheduleProgressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ScheduleProgressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_progress
     *
     * @mbggenerated
     */
    int countByExample(ScheduleProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_progress
     *
     * @mbggenerated
     */
    int deleteByExample(ScheduleProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_progress
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_progress
     *
     * @mbggenerated
     */
    int insert(ScheduleProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_progress
     *
     * @mbggenerated
     */
    int insertSelective(ScheduleProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_progress
     *
     * @mbggenerated
     */
    List<ScheduleProgress> selectByExampleWithRowbounds(ScheduleProgressExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_progress
     *
     * @mbggenerated
     */
    List<ScheduleProgress> selectByExample(ScheduleProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_progress
     *
     * @mbggenerated
     */
    ScheduleProgress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_progress
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ScheduleProgress record, @Param("example") ScheduleProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_progress
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ScheduleProgress record, @Param("example") ScheduleProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_progress
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ScheduleProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_progress
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ScheduleProgress record);
}