package com.yeahmobi.yscheduler.model.dao.mapper;

import com.yeahmobi.yscheduler.model.WorkflowTaskInstance;
import com.yeahmobi.yscheduler.model.WorkflowTaskInstanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WorkflowTaskInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_instance
     *
     * @mbggenerated
     */
    int countByExample(WorkflowTaskInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_instance
     *
     * @mbggenerated
     */
    int deleteByExample(WorkflowTaskInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_instance
     *
     * @mbggenerated
     */
    int insert(WorkflowTaskInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_instance
     *
     * @mbggenerated
     */
    int insertSelective(WorkflowTaskInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_instance
     *
     * @mbggenerated
     */
    List<WorkflowTaskInstance> selectByExampleWithRowbounds(WorkflowTaskInstanceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_instance
     *
     * @mbggenerated
     */
    List<WorkflowTaskInstance> selectByExample(WorkflowTaskInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_instance
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WorkflowTaskInstance record, @Param("example") WorkflowTaskInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_instance
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WorkflowTaskInstance record, @Param("example") WorkflowTaskInstanceExample example);
}