package com.yeahmobi.yscheduler.model.dao.mapper;

import com.yeahmobi.yscheduler.model.WorkflowInstance;
import com.yeahmobi.yscheduler.model.WorkflowInstanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WorkflowInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_instance
     *
     * @mbggenerated
     */
    int countByExample(WorkflowInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_instance
     *
     * @mbggenerated
     */
    int deleteByExample(WorkflowInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_instance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_instance
     *
     * @mbggenerated
     */
    int insert(WorkflowInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_instance
     *
     * @mbggenerated
     */
    int insertSelective(WorkflowInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_instance
     *
     * @mbggenerated
     */
    List<WorkflowInstance> selectByExampleWithRowbounds(WorkflowInstanceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_instance
     *
     * @mbggenerated
     */
    List<WorkflowInstance> selectByExample(WorkflowInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_instance
     *
     * @mbggenerated
     */
    WorkflowInstance selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_instance
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WorkflowInstance record, @Param("example") WorkflowInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_instance
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WorkflowInstance record, @Param("example") WorkflowInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_instance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WorkflowInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_instance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WorkflowInstance record);
}