package com.yeahmobi.yscheduler.model.dao.mapper;

import com.yeahmobi.yscheduler.model.WorkflowTaskDependency;
import com.yeahmobi.yscheduler.model.WorkflowTaskDependencyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WorkflowTaskDependencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_dependency
     *
     * @mbggenerated
     */
    int countByExample(WorkflowTaskDependencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_dependency
     *
     * @mbggenerated
     */
    int deleteByExample(WorkflowTaskDependencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_dependency
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_dependency
     *
     * @mbggenerated
     */
    int insert(WorkflowTaskDependency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_dependency
     *
     * @mbggenerated
     */
    int insertSelective(WorkflowTaskDependency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_dependency
     *
     * @mbggenerated
     */
    List<WorkflowTaskDependency> selectByExampleWithRowbounds(WorkflowTaskDependencyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_dependency
     *
     * @mbggenerated
     */
    List<WorkflowTaskDependency> selectByExample(WorkflowTaskDependencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_dependency
     *
     * @mbggenerated
     */
    WorkflowTaskDependency selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_dependency
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WorkflowTaskDependency record, @Param("example") WorkflowTaskDependencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_dependency
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WorkflowTaskDependency record, @Param("example") WorkflowTaskDependencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_dependency
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WorkflowTaskDependency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_task_dependency
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WorkflowTaskDependency record);
}