package com.yeahmobi.yscheduler.model.dao.mapper;

import com.yeahmobi.yscheduler.model.WorkflowDetail;
import com.yeahmobi.yscheduler.model.WorkflowDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WorkflowDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_detail
     *
     * @mbggenerated
     */
    int countByExample(WorkflowDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_detail
     *
     * @mbggenerated
     */
    int deleteByExample(WorkflowDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_detail
     *
     * @mbggenerated
     */
    int insert(WorkflowDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_detail
     *
     * @mbggenerated
     */
    int insertSelective(WorkflowDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_detail
     *
     * @mbggenerated
     */
    List<WorkflowDetail> selectByExampleWithRowbounds(WorkflowDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_detail
     *
     * @mbggenerated
     */
    List<WorkflowDetail> selectByExample(WorkflowDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_detail
     *
     * @mbggenerated
     */
    WorkflowDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WorkflowDetail record, @Param("example") WorkflowDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WorkflowDetail record, @Param("example") WorkflowDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WorkflowDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WorkflowDetail record);
}